---
- name: Testa os managed nodes
  hosts: localhost

  tasks:
    - name: executa ping 
      ping:
      register: resultado
      
    - name: exibe resultado
      debug: 
        msg: "{{ resultado }}"

